main: net.giantgames.replay.ReplayPlugin
name: ReplaySystem
authors: [Veraty, Exceptionflug]
version: 1.0-SNAPSHOT
depend: [ProtocolLib,PacketWrapper]

commands:

  replay:
    description: Replay Command
    default: op
    usage: replay [record,finish,play,stop,list,play]